/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package models;

import com.cdyne.ws.DocumentSummary;
import com.cdyne.ws.Words;
import java.util.List;

/**
 * A class that deals with web services. Specifically the spell checking
 * web service from CYDNE.
 * 
 * @author ad3-brown
 */
public class WebServiceSpellingChecker {

    /**
     * Takes a string of text, pushes it through the spell checking web-service
     * provided by CYDNE, and replaces the misspelled words with the first
     * suggestion. Additionally, appends a summary of the misspelled words onto
     * the corrected text.
     * 
     * Code adapted from the Netbeans web services tutorial:
     * https://netbeans.org/kb/docs/websvc/client.html
     * 
     * @param bodyText
     * @return
     */
    public static String checkAndFixSpelling(java.lang.String bodyText) {
        //Process result
        com.cdyne.ws.DocumentSummary doc = checkTextBodyV2(bodyText);
        String allContent = doc.getBody().trim();
        String result = allContent;

        //identify the number of wrongly spelled words:
        int noOfMistakes = doc.getMisspelledWordCount();
        int noReplaced = 0;
        String replacedWords = "";

        //identify the array of wrongly spelled words:
        List allWrongWords = doc.getMisspelledWord();

        for (Object wrongWord : allWrongWords) {
            String wrongWordString = ((Words) wrongWord).getWord();
            replacedWords += wrongWordString;
            
            List allSuggestions = ((Words) wrongWord).getSuggestions();
            // Make sure that there ARE actually valid suggestions.
            if (allSuggestions != null || !allSuggestions.isEmpty()) {
                String suggestion = (String) allSuggestions.get(0);
                result = result.replaceFirst(wrongWordString, suggestion);
                noReplaced++;
                replacedWords += " -> " + suggestion +".\n";
            } else {
                replacedWords += " -> No suitable replacement found.\n";
            }
        }

        // provide a summary of the findings.
        if (noOfMistakes != 0) {
            result += "\n\nNumber of wrong words: " + noOfMistakes
                    + "\nWrong words replaced with a suitable replacement: " + noReplaced
                    + "\n" + replacedWords;
        } else {
            result += "\n\nNo wrong words found!\n";
        }
        return result;
    }

    // Auto generated by the web service.
    private static DocumentSummary checkTextBodyV2(java.lang.String bodyText) {
        com.cdyne.ws.Check service = new com.cdyne.ws.Check();
        com.cdyne.ws.CheckSoap port = service.getCheckSoap();
        return port.checkTextBodyV2(bodyText);
    }
}
